#define yy_create_buffer funetak_yy_create_buffer
#define yy_delete_buffer funetak_yy_delete_buffer
#define yy_scan_buffer funetak_yy_scan_buffer
#define yy_scan_string funetak_yy_scan_string
#define yy_scan_bytes funetak_yy_scan_bytes
#define yy_flex_debug funetak_yy_flex_debug
#define yy_init_buffer funetak_yy_init_buffer
#define yy_flush_buffer funetak_yy_flush_buffer
#define yy_load_buffer_state funetak_yy_load_buffer_state
#define yy_switch_to_buffer funetak_yy_switch_to_buffer
#define yyin funetak_yyin
#define yyleng funetak_yyleng
#define yylex funetak_yylex
#define yyout funetak_yyout
#define yyrestart funetak_yyrestart
#define yytext funetak_yytext

#line 19 "funetak.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 137
#define YY_END_OF_BUFFER 138
static yyconst short int yy_accept[496] =
    {   0,
        0,    0,    0,    0,    0,    0,  138,  135,  134,  136,
      131,  135,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  135,  135,    0,    0,
       43,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   62,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   42,    0,    0,   80,
       81,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   96,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  115,    0,    0,   38,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  132,    0,    1,
        0,    0,    0,   47,    0,    0,    0,    0,    5,    0,
       51,   52,    0,   54,    6,    0,    0,    0,   59,    0,
       60,   61,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   70,    0,    0,    0,   73,    0,    0,    0,
        0,   76,    0,    0,    0,    0,   78,    0,    0,   20,
       82,    0,    0,    0,    0,    0,    0,    0,   88,    0,
        0,   91,    0,    0,   94,    0,    0,    0,    0,    0,

       24,    0,    0,    0,    0,    0,    0,   27,    0,   29,
        0,    0,    0,  105,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       45,    0,   48,    0,    3,    0,    0,    0,    0,   55,
        0,    0,    0,    0,   63,    0,    0,    0,    0,    0,
       11,    0,    0,    0,    0,   71,    0,   13,    0,    0,
        0,   75,    0,    0,    0,   77,    0,    0,   19,   83,
        0,    0,    0,    0,    0,   87,    0,    0,   92,   93,
        0,   23,   97,    0,    0,    0,    0,    0,  103,    0,

        0,   28,    0,    0,    0,    0,    0,    0,  108,    0,
      110,    0,    0,    0,    0,  114,    0,    0,    0,    0,
        0,   37,    0,  123,   39,  124,  125,    0,    0,    0,
      129,   41,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   58,    0,   64,    0,    0,    9,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,   16,
       17,   18,    0,   21,   22,   84,    0,   86,   89,   90,
        0,   98,   99,    0,    0,    0,   26,  104,    0,   31,
        0,  106,    0,    0,    0,  109,  111,  112,  113,    0,
        0,    0,    0,    0,   36,    0,    0,  126,    0,   40,

        0,    0,    0,   44,    0,    0,    0,    0,   50,    0,
       56,   57,    7,    8,    0,    0,    0,   67,   68,   69,
        0,   14,   74,   15,    0,    0,    0,    0,    0,    0,
        0,   32,    0,    0,    0,    0,  121,  116,    0,    0,
        0,    0,    0,  127,  128,  130,  133,    0,    0,   49,
        0,    0,    0,    0,   66,    0,    0,    0,    0,  100,
        0,   25,  102,    0,    0,    0,   34,   35,    0,    0,
        0,  120,  122,   46,    2,    4,    0,   65,   10,   72,
       79,   85,   95,  101,   30,  107,   33,  117,  118,    0,
       53,    0,    0,  119,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    7,
        1,    8,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       19,   25,   26,   27,   28,   19,   29,   19,   30,   31,
        1,    1,    1,    1,    1,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   18,   41,   42,   43,   44,
       45,   46,   19,   47,   48,   49,   50,   51,   52,   53,
       54,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst short int yy_base[499] =
    {   0,
        0,    0,    0,    0,   53,   55,  969,  970,  970,  970,
      970,  963,  101,   24,   27,   30,   22,   41,   47,   62,
      152,  917,   78,   79,   77,   82,   92,   80,  126,  134,
      920,  138,  920,  932,  148,  163,  924,  204,  957,  953,
      970,  915,   21,  212,   82,  923,  910,  220,  912,  228,
      902,  923,  905,  236,  909,  119,  898,  916,  914,  914,
      902,  909,  910,  911,   43,   37,  899,  909,  893,  102,
      905,  892,   93,  896,   15,  894,  970,  894,  244,  970,
      970,  252,  124,  893,  902,  885,  892,  260,  885,  897,
      268,  894,  138,   92,  970,  182,  890,  879,  882,  892,

      880,  892,  888,  148,  145,  880,  232,  277,  874,  876,
      877,  251,  875,   65,  885,  245,  970,  868,  883,  252,
      242,  874,  863,  866,  877,  246,  865,  970,  901,  970,
      858,  301,  867,  970,  309,  873,  318,  866,  970,  864,
      970,  970,  863,  970,  970,  326,  844,  847,  970,  845,
      970,  970,  833,  843,  824,  829,  817,  814,  102,  809,
      819,  807,  970,  800,  798,  798,  784,  787,  781,  788,
      769,  970,  769,  773,  334,  771,  970,  766,  342,  970,
      970,  350,  758,  744,  755,  738,  735,  739,  970,  735,
      731,  970,  732,  729,  970,  723,  358,  366,  703,  715,

      970,  703,  702,  708,  700,  697,  691,  970,  374,  970,
      683,  670,  667,  970,  662,  677,  655,  660,  646,  382,
      249,  643,  651,  653,  647,  261,  633,  390,  627,  620,
      624,  619,  616,  618,  605,  596,  398,  593,  593,  582,
      970,  591,  970,  578,  970,  617,  568,  572,  564,  970,
      550,  561,  406,  556,  970,  414,  535,  541,  423,  532,
      970,  540,  524,  536,  517,  970,  431,  970,  523,  519,
      523,  970,  501,  439,  447,  970,  455,  500,  970,  970,
      463,  471,  479,  509,  487,  970,  495,  503,  970,  970,
      492,  970,  970,  511,  486,  489,  489,  481,  970,  519,

      527,  970,  477,  535,  473,  543,  469,  471,  970,  551,
      970,  465,  458,  559,  455,  443,  431,  441,  440,  427,
      420,  970,  463,  970,  970,  970,  970,  567,  426,  423,
      970,  970,  399,  415,  577,  404,  402,  386,  385,  585,
      387,  593,  373,  970,  601,  970,  609,  370,  970,  365,
      363,  617,  625,  633,  970,  360,  641,  649,  657,  970,
      970,  970,  366,  970,  970,  970,  349,  970,  970,  970,
      354,  970,  970,  352,  337,  344,  970,  970,  334,  970,
      337,  970,  326,  326,  307,  970,  970,  970,  970,  315,
      665,  673,  304,  300,  296,  278,  273,  970,  681,  970,

      689,  697,  705,  970,  269,  261,  713,  277,  970,  258,
      970,  970,  970,  970,  260,  220,  721,  970,  970,  970,
      228,  970,  970,  970,  229,  204,  222,  729,  737,  207,
      210,  970,  204,  201,  745,  753,  970,  970,  180,  198,
      194,  761,  771,  970,  970,  970,  970,  779,  787,  970,
      795,  168,  803,  811,  970,  819,  827,  835,  156,  970,
      843,  970,  970,  851,  859,  145,  970,  970,  867,  875,
      112,  970,  970,  970,  970,  970,  883,  970,  970,  970,
      970,  970,  970,  970,  970,  970,  970,  970,  970,   76,
      970,   42,  891,  970,  970,  899,   62,  901

    } ;

static yyconst short int yy_def[499] =
    {   0,
      495,    1,    1,    1,  496,  496,  495,  495,  495,  495,
      495,  497,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  497,  498,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  498,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,    0,  495,  495,  495

    } ;

static yyconst short int yy_nxt[1025] =
    {   0,
        8,    9,   10,   11,    8,   11,   12,    8,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   11,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   13,   14,   15,   16,   17,   18,   19,   35,   21,
       11,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       11,   36,   11,   33,    9,   10,    9,   10,   55,   50,
      176,   57,  132,   40,   61,   62,  177,  133,   51,   58,
       52,   56,   64,   53,   59,   63,   37,   54,   37,   60,
       65,  162,   69,  163,  159,   66,  164,   67,  493,  160,
       68,   70,   38,   72,   38,  161,   71,   73,   37,  224,

       37,   41,   41,   41,   74,   41,   75,   41,   41,   84,
       87,   76,   92,  225,   88,  102,  135,   85,   95,  103,
      492,   93,   86,   89,  173,   96,   94,   99,   90,  104,
       97,   98,   91,   42,  196,  136,  100,  261,  101,  174,
      197,  168,   43,   44,   45,  169,  170,   46,   47,   48,
      262,   49,   77,   77,   77,   78,   77,  105,   77,   77,
      490,  106,  147,  148,  107,  111,  149,  183,  150,  118,
      108,  184,  112,  113,  109,  110,  119,  120,  114,   72,
      115,  194,  121,   73,  122,  116,  195,  125,   79,  207,
       74,  208,   75,  487,  118,   80,  209,   76,  210,   81,

       82,  119,  126,  483,  128,  128,  128,  121,  128,  122,
      128,  128,  134,  134,  134,  477,  134,  198,  134,  134,
      139,  139,  139,  199,  139,  471,  139,  139,  141,  141,
      141,  470,  141,  469,  141,  141,  145,  145,  145,  466,
      145,  465,  145,  145,  180,  180,  180,  464,  180,  463,
      180,  180,  181,  181,  181,  459,  181,  458,  181,  181,
      189,  189,  189,  457,  189,  456,  189,  189,  192,  192,
      192,  212,  192,  454,  192,  192,  213,  214,  214,  214,
      227,  214,  219,  214,  214,  231,  220,  232,  234,  228,
      221,  235,  313,  232,  233,  222,  314,  319,  453,  182,

      233,  241,  241,  241,  320,  241,  452,  241,  241,  243,
      243,  243,  451,  243,  449,  243,  243,  448,  245,  245,
      245,  443,  245,  215,  245,  245,  250,  250,  250,  251,
      250,  442,  250,  250,  276,  276,  276,  441,  276,  440,
      276,  276,  279,  279,  279,  439,  279,  133,  279,  279,
      280,  280,  280,  436,  280,  435,  280,  280,  292,  292,
      292,  246,  292,  434,  292,  292,  293,  293,  293,  433,
      293,  432,  293,  293,  302,  302,  302,  431,  302,  430,
      302,  302,  311,  311,  311,  429,  311,  428,  311,  311,
      322,  322,  322,  427,  322,  426,  322,  322,  331,  331,

      331,  425,  331,  421,  331,  331,  344,  344,  344,  417,
      344,  416,  344,  344,  346,  346,  346,  415,  346,  412,
      346,  346,  410,  349,  349,  349,  408,  349,  312,  349,
      349,  355,  355,  355,  407,  355,  406,  355,  355,  360,
      360,  360,  405,  360,  332,  360,  360,  361,  361,  361,
      403,  361,  402,  361,  361,  362,  362,  362,  401,  362,
      400,  362,  362,  364,  364,  364,  397,  364,  396,  364,
      364,  365,  365,  365,  395,  365,  394,  365,  365,  366,
      366,  366,  393,  366,  392,  366,  366,  368,  368,  368,
      391,  368,  390,  368,  368,  369,  369,  369,  388,  369,

      387,  369,  369,  370,  370,  370,  385,  370,  384,  370,
      370,  372,  372,  372,  381,  372,  379,  372,  372,  377,
      377,  377,  376,  377,  375,  377,  377,  378,  378,  378,
      374,  378,  373,  378,  378,  380,  380,  380,  371,  380,
      367,  380,  380,  382,  382,  382,  363,  382,  359,  382,
      382,  386,  386,  386,  358,  386,  357,  386,  386,  389,
      389,  389,  356,  389,  354,  389,  389,  398,  398,  398,
      353,  398,  352,  398,  398,  351,  350,  404,  404,  404,
      348,  404,  383,  404,  404,  409,  409,  409,  347,  409,
      345,  409,  409,  411,  411,  411,  343,  411,  342,  411,

      411,  413,  413,  413,  341,  413,  340,  413,  413,  414,
      414,  414,  339,  414,  399,  414,  414,  418,  418,  418,
      338,  418,  337,  418,  418,  419,  419,  419,  336,  419,
      335,  419,  419,  420,  420,  420,  334,  420,  333,  420,
      420,  422,  422,  422,  330,  422,  329,  422,  422,  423,
      423,  423,  328,  423,  327,  423,  423,  424,  424,  424,
      326,  424,  325,  424,  424,  437,  437,  437,  324,  437,
      323,  437,  437,  438,  438,  438,  321,  438,  318,  438,
      438,  444,  444,  444,  317,  444,  316,  444,  444,  445,
      445,  445,  315,  445,  310,  445,  445,  446,  446,  446,

      309,  446,  308,  446,  446,  447,  447,  447,  307,  447,
      306,  447,  447,  450,  450,  450,  305,  450,  304,  450,
      450,  455,  455,  455,  303,  455,  301,  455,  455,  460,
      460,  460,  300,  460,  299,  460,  460,  462,  462,  462,
      298,  462,  297,  462,  462,  467,  467,  467,  296,  467,
      295,  467,  467,  468,  468,  468,  294,  468,  291,  468,
      468,  472,  472,  472,  290,  472,  289,  472,  472,  288,
      287,  473,  473,  473,  286,  473,  461,  473,  473,  474,
      474,  474,  285,  474,  284,  474,  474,  475,  475,  475,
      283,  475,  282,  475,  475,  476,  476,  476,  281,  476,

      278,  476,  476,  478,  478,  478,  277,  478,  275,  478,
      478,  479,  479,  479,  274,  479,  273,  479,  479,  480,
      480,  480,  272,  480,  271,  480,  480,  481,  481,  481,
      270,  481,  269,  481,  481,  482,  482,  482,  268,  482,
      267,  482,  482,  484,  484,  484,  266,  484,  265,  484,
      484,  485,  485,  485,  264,  485,  263,  485,  485,  486,
      486,  486,  260,  486,  259,  486,  486,  488,  488,  488,
      258,  488,  257,  488,  488,  489,  489,  489,  256,  489,
      255,  489,  489,  491,  491,  491,  254,  491,  253,  491,
      491,  494,  494,  494,  252,  494,  249,  494,  494,    8,

        8,  129,  129,  248,  247,  244,  242,  240,  130,  239,
      231,  238,  237,  236,  230,  229,  226,  223,  218,  217,
      216,  211,  206,  205,  204,  203,  202,  201,  200,  193,
      191,  190,  188,  187,  186,  185,  179,  178,  175,  172,
      171,  167,  166,  165,  158,  157,  156,  155,  154,  153,
      152,  151,  146,  144,  143,  142,  140,  138,  137,  131,
      130,  495,  127,  124,  123,  117,   83,   39,  495,    7,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495
    } ;

static yyconst short int yy_chk[1025] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,   15,   14,
       75,   16,   43,  497,   17,   17,   75,   43,   14,   16,
       14,   15,   18,   14,   16,   17,    5,   14,    6,   16,
       18,   66,   19,   66,   65,   18,   66,   18,  492,   65,
       18,   19,    5,   20,    6,   65,   19,   20,    5,  114,

        6,   13,   13,   13,   20,   13,   20,   13,   13,   23,
       24,   20,   25,  114,   24,   28,   45,   23,   26,   28,
      490,   25,   23,   24,   73,   26,   25,   27,   24,   28,
       26,   26,   24,   13,   94,   45,   27,  159,   27,   73,
       94,   70,   13,   13,   13,   70,   70,   13,   13,   13,
      159,   13,   21,   21,   21,   21,   21,   29,   21,   21,
      471,   29,   56,   56,   29,   30,   56,   83,   56,   32,
       29,   83,   30,   30,   29,   29,   32,   32,   30,   35,
       30,   93,   32,   35,   32,   30,   93,   35,   21,  104,
       35,  104,   35,  466,   36,   21,  105,   35,  105,   21,

       21,   36,   36,  459,   38,   38,   38,   36,   38,   36,
       38,   38,   44,   44,   44,  452,   44,   96,   44,   44,
       48,   48,   48,   96,   48,  441,   48,   48,   50,   50,
       50,  440,   50,  439,   50,   50,   54,   54,   54,  434,
       54,  433,   54,   54,   79,   79,   79,  431,   79,  430,
       79,   79,   82,   82,   82,  427,   82,  426,   82,   82,
       88,   88,   88,  425,   88,  421,   88,   88,   91,   91,
       91,  107,   91,  416,   91,   91,  107,  108,  108,  108,
      116,  108,  112,  108,  108,  120,  112,  126,  121,  116,
      112,  121,  221,  120,  126,  112,  221,  226,  415,   82,

      120,  132,  132,  132,  226,  132,  410,  132,  132,  135,
      135,  135,  408,  135,  406,  135,  135,  405,  137,  137,
      137,  397,  137,  108,  137,  137,  146,  146,  146,  146,
      146,  396,  146,  146,  175,  175,  175,  395,  175,  394,
      175,  175,  179,  179,  179,  393,  179,  132,  179,  179,
      182,  182,  182,  390,  182,  385,  182,  182,  197,  197,
      197,  137,  197,  384,  197,  197,  198,  198,  198,  383,
      198,  381,  198,  198,  209,  209,  209,  379,  209,  376,
      209,  209,  220,  220,  220,  375,  220,  374,  220,  220,
      228,  228,  228,  371,  228,  367,  228,  228,  237,  237,

      237,  363,  237,  356,  237,  237,  253,  253,  253,  351,
      253,  350,  253,  253,  256,  256,  256,  348,  256,  343,
      256,  256,  341,  259,  259,  259,  339,  259,  220,  259,
      259,  267,  267,  267,  338,  267,  337,  267,  267,  274,
      274,  274,  336,  274,  237,  274,  274,  275,  275,  275,
      334,  275,  333,  275,  275,  277,  277,  277,  330,  277,
      329,  277,  277,  281,  281,  281,  323,  281,  321,  281,
      281,  282,  282,  282,  320,  282,  319,  282,  282,  283,
      283,  283,  318,  283,  317,  283,  283,  285,  285,  285,
      316,  285,  315,  285,  285,  287,  287,  287,  313,  287,

      312,  287,  287,  288,  288,  288,  308,  288,  307,  288,
      288,  294,  294,  294,  305,  294,  303,  294,  294,  300,
      300,  300,  298,  300,  297,  300,  300,  301,  301,  301,
      296,  301,  295,  301,  301,  304,  304,  304,  291,  304,
      284,  304,  304,  306,  306,  306,  278,  306,  273,  306,
      306,  310,  310,  310,  271,  310,  270,  310,  310,  314,
      314,  314,  269,  314,  265,  314,  314,  328,  328,  328,
      264,  328,  263,  328,  328,  262,  260,  335,  335,  335,
      258,  335,  306,  335,  335,  340,  340,  340,  257,  340,
      254,  340,  340,  342,  342,  342,  252,  342,  251,  342,

      342,  345,  345,  345,  249,  345,  248,  345,  345,  347,
      347,  347,  247,  347,  328,  347,  347,  352,  352,  352,
      246,  352,  244,  352,  352,  353,  353,  353,  242,  353,
      240,  353,  353,  354,  354,  354,  239,  354,  238,  354,
      354,  357,  357,  357,  236,  357,  235,  357,  357,  358,
      358,  358,  234,  358,  233,  358,  358,  359,  359,  359,
      232,  359,  231,  359,  359,  391,  391,  391,  230,  391,
      229,  391,  391,  392,  392,  392,  227,  392,  225,  392,
      392,  399,  399,  399,  224,  399,  223,  399,  399,  401,
      401,  401,  222,  401,  219,  401,  401,  402,  402,  402,

      218,  402,  217,  402,  402,  403,  403,  403,  216,  403,
      215,  403,  403,  407,  407,  407,  213,  407,  212,  407,
      407,  417,  417,  417,  211,  417,  207,  417,  417,  428,
      428,  428,  206,  428,  205,  428,  428,  429,  429,  429,
      204,  429,  203,  429,  429,  435,  435,  435,  202,  435,
      200,  435,  435,  436,  436,  436,  199,  436,  196,  436,
      436,  442,  442,  442,  194,  442,  193,  442,  442,  191,
      190,  443,  443,  443,  188,  443,  428,  443,  443,  448,
      448,  448,  187,  448,  186,  448,  448,  449,  449,  449,
      185,  449,  184,  449,  449,  451,  451,  451,  183,  451,

      178,  451,  451,  453,  453,  453,  176,  453,  174,  453,
      453,  454,  454,  454,  173,  454,  171,  454,  454,  456,
      456,  456,  170,  456,  169,  456,  456,  457,  457,  457,
      168,  457,  167,  457,  457,  458,  458,  458,  166,  458,
      165,  458,  458,  461,  461,  461,  164,  461,  162,  461,
      461,  464,  464,  464,  161,  464,  160,  464,  464,  465,
      465,  465,  158,  465,  157,  465,  465,  469,  469,  469,
      156,  469,  155,  469,  469,  470,  470,  470,  154,  470,
      153,  470,  470,  477,  477,  477,  150,  477,  148,  477,
      477,  493,  493,  493,  147,  493,  143,  493,  493,  496,

      496,  498,  498,  140,  138,  136,  133,  131,  129,  127,
      125,  124,  123,  122,  119,  118,  115,  113,  111,  110,
      109,  106,  103,  102,  101,  100,   99,   98,   97,   92,
       90,   89,   87,   86,   85,   84,   78,   76,   74,   72,
       71,   69,   68,   67,   64,   63,   62,   61,   60,   59,
       58,   57,   55,   53,   52,   51,   49,   47,   46,   42,
       40,   39,   37,   34,   33,   31,   22,   12,    7,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "funetak.l"
#define INITIAL 0
/* GNU Talkfilters
   Copyright (C) 1998-2003 Free Software Foundation, Inc.

   This file is part of GNU Talkfilters

   GNU Talkfilters is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2, or (at
   your option) any later version.

   This software is distributed in the hope that it will be amusing, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this software; see the file COPYING.  If not, write to the
   Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* static char version[] = "funetak. v1.2. Eclipse Enterprises"; */
#line 35 "funetak.l"

#include "common.h"
#include "talkfilters.h"

#define YY_DECL int yylex(gtf_databuf_t *buf)

#define NIW 1
#define INW 2

#line 805 "funetak.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 50 "funetak.l"


#line 959 "funetak.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 496 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 970 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 54 "funetak.l"
gtf_echo(); // don't damage HTML tags
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 56 "funetak.l"
gtf_puts_case("uni boodi");
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "funetak.l"
gtf_puts_case("ure");
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 58 "funetak.l"
gtf_puts_case("uss hool");
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 59 "funetak.l"
gtf_puts_case("et");
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 60 "funetak.l"
gtf_puts_case("bi");
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 61 "funetak.l"
gtf_puts_case("cud");
	YY_BREAK
case 8:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 62 "funetak.l"
gtf_puts_case("umpti");
	YY_BREAK
case 9:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "funetak.l"
gtf_puts_case("i's");
	YY_BREAK
case 10:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 64 "funetak.l"
gtf_puts_case("fuctawri");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "funetak.l"
gtf_puts_case("fuel"); BEGIN(INW);
	YY_BREAK
case 12:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "funetak.l"
gtf_puts_case("frum");
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "funetak.l"
gtf_puts_case("fak"); BEGIN(INW);
	YY_BREAK
case 14:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 68 "funetak.l"
gtf_puts_case("go en");
	YY_BREAK
case 15:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 69 "funetak.l"
gtf_puts_case("gus");
	YY_BREAK
case 16:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 70 "funetak.l"
gtf_puts_case("hup");
	YY_BREAK
case 17:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "funetak.l"
gtf_puts_case("hear");
	YY_BREAK
case 18:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 72 "funetak.l"
gtf_puts_case("hup");
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "funetak.l"
gtf_puts_case("eye em");
	YY_BREAK
case 20:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "funetak.l"
gtf_puts_case("uf");
	YY_BREAK
case 21:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "funetak.l"
gtf_puts_case("joonk");
	YY_BREAK
case 22:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "funetak.l"
gtf_puts_case("juzst");
	YY_BREAK
case 23:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "funetak.l"
gtf_puts_case("noot");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "funetak.l"
gtf_puts_case("ut"); BEGIN(INW);
	YY_BREAK
case 25:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 79 "funetak.l"
gtf_puts_case("puket");
	YY_BREAK
case 26:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 80 "funetak.l"
gtf_puts_case("wide");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "funetak.l"
gtf_puts_case("wun"); BEGIN(INW);
	YY_BREAK
case 28:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 82 "funetak.l"
gtf_puts_case("sor");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "funetak.l"
gtf_puts_case("sa"); BEGIN(INW);
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 84 "funetak.l"
gtf_puts_case("sulen");
	YY_BREAK
case 31:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 85 "funetak.l"
gtf_puts_case("shiet");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "funetak.l"
{ if(gtf_random(4))
			    gtf_puts_case("sud");
			  else
			    gtf_puts_case("shud");
			  BEGIN(INW);
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "funetak.l"
gtf_puts_case("stwait"); BEGIN(INW);
	YY_BREAK
case 34:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "funetak.l"
gtf_puts_case("soon sut");
	YY_BREAK
case 35:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 94 "funetak.l"
gtf_puts_case("tho");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "funetak.l"
gtf_puts_case("twains"); BEGIN(INW);
	YY_BREAK
case 37:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 96 "funetak.l"
gtf_puts_case("to");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "funetak.l"
gtf_puts_case("oop"); BEGIN(INW);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "funetak.l"
gtf_puts_case("wutch"); BEGIN(INW);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "funetak.l"
gtf_puts_case("wud"); BEGIN(INW);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "funetak.l"
gtf_puts_case("ur"); BEGIN(INW);
	YY_BREAK
case 42:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 101 "funetak.l"
gtf_puts_case("em");
	YY_BREAK
case 43:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 102 "funetak.l"
gtf_puts_case("ar");
	YY_BREAK
case 44:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 103 "funetak.l"
gtf_puts_case("abut");
	YY_BREAK
case 45:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 104 "funetak.l"
gtf_puts_case("awl");
	YY_BREAK
case 46:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 105 "funetak.l"
gtf_puts_case("awl wight");
	YY_BREAK
case 47:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 106 "funetak.l"
gtf_puts_case("um");
	YY_BREAK
case 48:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 107 "funetak.l"
gtf_puts_case("en");
	YY_BREAK
case 49:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 108 "funetak.l"
gtf_puts_case("r ent");
	YY_BREAK
case 50:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 109 "funetak.l"
gtf_puts_case("av void");
	YY_BREAK
case 51:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "funetak.l"
gtf_puts_case("b");
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "funetak.l"
gtf_puts_case("boi"); BEGIN(INW);
	YY_BREAK
case 53:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "funetak.l"
gtf_puts_case("bruketz");
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "funetak.l"
gtf_puts_case("bot"); BEGIN(INW);
	YY_BREAK
case 55:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 114 "funetak.l"
gtf_puts_case("kun");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 115 "funetak.l"
{ if(gtf_random(4))
			    gtf_puts_case("car ent");
			  else
			    gtf_puts_case("kunt");
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "funetak.l"
gtf_puts_case("cunvur"); BEGIN(INW);
	YY_BREAK
case 58:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 121 "funetak.l"
gtf_puts_case("kewl");
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 "funetak.l"
gtf_puts_case("cuz"); BEGIN(INW);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "funetak.l"
gtf_puts_case("di"); BEGIN(INW);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "funetak.l"
gtf_puts_case("ded"); BEGIN(INW);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "funetak.l"
gtf_puts_case("dew"); BEGIN(INW);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "funetak.l"
{ if (gtf_random(3)) gtf_puts_case("dus");
			  else gtf_puts_case("duz");
			  BEGIN(INW); }
	YY_BREAK
case 64:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "funetak.l"
gtf_puts_case("do ed");
	YY_BREAK
case 65:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "funetak.l"
gtf_puts_case("unglush");
	YY_BREAK
case 66:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 131 "funetak.l"
gtf_puts_case("felt her");
	YY_BREAK
case 67:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 132 "funetak.l"
gtf_puts_case("fuzt");
	YY_BREAK
case 68:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 133 "funetak.l"
gtf_puts_case("fuckzed");
	YY_BREAK
case 69:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 134 "funetak.l"
gtf_puts_case("fulz");
	YY_BREAK
case 70:
#line 136 "funetak.l"
case 71:
YY_RULE_SETUP
#line 136 "funetak.l"
gtf_puts_case("vor"); BEGIN(INW);
	YY_BREAK
case 72:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 137 "funetak.l"
gtf_puts_case("gut en");
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "funetak.l"
gtf_puts_case("gut"); BEGIN(INW);
	YY_BREAK
case 74:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 139 "funetak.l"
{ if(gtf_random(2))
			    gtf_puts_case("gun nar");
			  else
			    gtf_puts_case("gunna");
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "funetak.l"
gtf_puts_case("gud"); BEGIN(INW);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "funetak.l"
gtf_puts_case("huz"); BEGIN(INW);
	YY_BREAK
case 77:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 146 "funetak.l"
gtf_puts_case("humm");
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "funetak.l"
gtf_puts_case("huw"); BEGIN(INW);
	YY_BREAK
case 79:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 148 "funetak.l"
gtf_puts_case("hundrud");
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 149 "funetak.l"
gtf_puts_case("un"); BEGIN(INW);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 150 "funetak.l"
{ if(gtf_random(5))
			    gtf_puts_case("ez");
			  else
			    gtf_puts_case("uz");
			  BEGIN(INW);
			}
	YY_BREAK
case 82:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 156 "funetak.l"
{ if(gtf_random(5))
			    gtf_puts_case("et");
			  else
			    gtf_puts_case("ut");
			}
	YY_BREAK
case 83:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 161 "funetak.l"
gtf_puts_case("etz");
	YY_BREAK
case 84:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 162 "funetak.l"
{ if(gtf_random(7))
			    gtf_puts_case("lye em");
			  else
			    gtf_puts_case("lyem");
			}
	YY_BREAK
case 85:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 167 "funetak.l"
gtf_puts_case("wibwari");
	YY_BREAK
case 86:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 168 "funetak.l"
gtf_puts_case("wuntz");
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 169 "funetak.l"
gtf_puts_case("muk"); BEGIN(INW);
	YY_BREAK
case 88:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 170 "funetak.l"
gtf_puts_case("mi");
	YY_BREAK
case 89:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 171 "funetak.l"
gtf_puts_case("mur");
	YY_BREAK
case 90:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 172 "funetak.l"
gtf_puts_case("mutch");
	YY_BREAK
case 91:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 173 "funetak.l"
gtf_puts_case("mi");
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 174 "funetak.l"
gtf_puts_case("nud"); BEGIN(INW);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 175 "funetak.l"
gtf_puts_case("noon"); BEGIN(INW);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 176 "funetak.l"
gtf_puts_case("nut"); BEGIN(INW);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 177 "funetak.l"
gtf_puts_case("numerekz");
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 178 "funetak.l"
gtf_puts_case("uf"); BEGIN(INW);
	YY_BREAK
case 97:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 179 "funetak.l"
gtf_puts_case("wun");
	YY_BREAK
case 98:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 180 "funetak.l"
gtf_puts_case("own we");
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 181 "funetak.l"
gtf_puts_case("udder"); BEGIN(INW);
	YY_BREAK
case 100:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 182 "funetak.l"
gtf_puts_case("poopel");
	YY_BREAK
case 101:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 183 "funetak.l"
gtf_puts_case("poopelz");
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 184 "funetak.l"
gtf_puts_case("prublim"); BEGIN(INW);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 185 "funetak.l"
gtf_puts_case("wed"); BEGIN(INW);
	YY_BREAK
case 104:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 186 "funetak.l"
gtf_puts_case("wul");
	YY_BREAK
case 105:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 187 "funetak.l"
gtf_puts_case("zo");
	YY_BREAK
case 106:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 188 "funetak.l"
gtf_puts_case("surt");
	YY_BREAK
case 107:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 189 "funetak.l"
gtf_puts_case("surten");
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 190 "funetak.l"
gtf_puts_case("tak"); BEGIN(INW);
	YY_BREAK
case 109:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 191 "funetak.l"
{ if(gtf_random(4))
			    gtf_puts_case("dat");
			  else
			    gtf_puts_case("dut");
			}
	YY_BREAK
case 110:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 196 "funetak.l"
gtf_puts_case("da");
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 197 "funetak.l"
gtf_puts_case("der"); BEGIN(INW);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 198 "funetak.l"
gtf_puts_case("tunk"); BEGIN(INW);
	YY_BREAK
case 113:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 199 "funetak.l"
{ if(gtf_random(2) == 0)
			    gtf_puts_case("des");
			  else if(gtf_random(3) == 0)
			    gtf_puts_case("dis");
			  else if(gtf_random(3) == 0)
			    gtf_puts_case("dus");
			  else gtf_puts_case("duz");
			}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 207 "funetak.l"
gtf_puts_case("tym"); BEGIN(INW);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "funetak.l"
gtf_puts_case("two"); BEGIN(INW);
	YY_BREAK
case 116:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 209 "funetak.l"
gtf_puts_case("tow di");
	YY_BREAK
case 117:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 210 "funetak.l"
gtf_puts_case("toate awli");
	YY_BREAK
case 118:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 211 "funetak.l"
gtf_puts_case("twufak");
	YY_BREAK
case 119:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 212 "funetak.l"
gtf_puts_case("twunz waiter");
	YY_BREAK
case 120:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 213 "funetak.l"
gtf_puts_case("twunti");
	YY_BREAK
case 121:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 214 "funetak.l"
gtf_puts_case("tymz");
	YY_BREAK
case 122:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 215 "funetak.l"
gtf_puts_case("wuz ent");
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 216 "funetak.l"
gtf_puts_case("wut"); BEGIN(INW);
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 217 "funetak.l"
gtf_puts_case("wul"); BEGIN(INW);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 218 "funetak.l"
gtf_puts_case("wif"); BEGIN(INW);
	YY_BREAK
case 126:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 219 "funetak.l"
gtf_puts_case("wud");
	YY_BREAK
case 127:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 220 "funetak.l"
gtf_puts_case("wudz");
	YY_BREAK
case 128:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 221 "funetak.l"
gtf_puts_case("wyt");
	YY_BREAK
case 129:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 222 "funetak.l"
gtf_puts_case("ewe");
	YY_BREAK
case 130:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 223 "funetak.l"
gtf_puts_case("zipi");
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 225 "funetak.l"
{ BEGIN(INW); gtf_echo(); }
	YY_BREAK


case 132:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 231 "funetak.l"
gtf_puts_case("eye"); BEGIN(NIW);
	YY_BREAK
case 133:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 232 "funetak.l"
gtf_puts_case("fune"); BEGIN(NIW);
	YY_BREAK

case 134:
YY_RULE_SETUP
#line 236 "funetak.l"
/* ignore trailing EOT character */
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 237 "funetak.l"
gtf_echo();
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 238 "funetak.l"
gtf_echo();
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 240 "funetak.l"
ECHO;
	YY_BREAK
#line 2022 "funetak.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NIW):
case YY_STATE_EOF(INW):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 496 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 496 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 495);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 240 "funetak.l"


/*
 */

#ifdef LIBRARY_MODE

int gtf_filter_funetak(const char *input, char *buf, size_t bufsz)
  {
  gtf_databuf_t buffer;
  YY_BUFFER_STATE _yybuf;

  gtf_strbuf_init(&buffer, buf, bufsz);
  _yybuf = yy_scan_string(input);
  yylex(&buffer);
  yy_delete_buffer(_yybuf);
  gtf_reset();

  return(buffer.overflow);
  }

int __gtf_filter_funetak(const char *input, char *buf, size_t bufsz)
{
  return(gtf_filter_funetak(input, buf, bufsz));
}

#else /* LIBRARY_MODE */

int main(int argc, char **argv)
  {
  gtf_parse_args();
  gtf_random_seed();

  yylex(NULL);

  return(EXIT_SUCCESS);
  }

#endif /* LIBRARY_MODE */

/* end of source file */
