#define yy_create_buffer pirate_yy_create_buffer
#define yy_delete_buffer pirate_yy_delete_buffer
#define yy_scan_buffer pirate_yy_scan_buffer
#define yy_scan_string pirate_yy_scan_string
#define yy_scan_bytes pirate_yy_scan_bytes
#define yy_flex_debug pirate_yy_flex_debug
#define yy_init_buffer pirate_yy_init_buffer
#define yy_flush_buffer pirate_yy_flush_buffer
#define yy_load_buffer_state pirate_yy_load_buffer_state
#define yy_switch_to_buffer pirate_yy_switch_to_buffer
#define yyin pirate_yyin
#define yyleng pirate_yyleng
#define yylex pirate_yylex
#define yyout pirate_yyout
#define yyrestart pirate_yyrestart
#define yytext pirate_yytext

#line 19 "pirate.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
static yyconst short int yy_acclist[208] =
    {   0,
      104,  102,  103,  101,  102,  103,  103,   96,  102,  103,
      102,  103,   96,  102,  103,   96,  102,  103,   96,  102,
      103,   96,  102,  103,   96,  102,  103,   96,  102,  103,
       96,  102,  103,   96,  102,  103,   96,  102,  103,   96,
      102,  103,   96,  102,  103,   96,  102,  103,   96,  102,
      103,   96,  102,  103,   96,  102,  103,   96,  102,  103,
       96,  102,  103,   96,  102,  103,   96,  102,  103,   96,
      102,  103,   96,  102,  103,   96,  102,  103,   96,  102,
      103,   96,  102,  103,  100,  102,  103,  100,  101,  102,
      103,  100,  103,   97,  100,  102,  103,   98,  100,  102,

      103,   99,  100,  102,  103,   36,    1,   49,   33,   57,
       63,16428,    3,   28,   22,   50,   83,   47,   73,16430,
       43,   54,   54,   56,   53,   53,   55,   78, 8236,   20,
       26,   77,   58,   21,    2,   27,   11,   62,   87,    4,
       48,   74,   82, 8238,   25,   65,   41,   18,   59,   37,
       52,   39,   24,   66,   81,   40,   10,   38,   84,   23,
       23,   94,   95,    7,16429,   42,   93,   64,   17,   16,
       68,   60,   75,   35,   19,   31,   91,    8, 8237,   12,
       30,    9,   86,   89,   69,   76,   32,   34,    6,    5,
       85,   92,   80,   67,    6,   13,   71,   79,   70,   61,

       88,   51,   14,   72,   90,   15,   29
    } ;

static yyconst short int yy_accept[474] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        8,   11,   13,   16,   19,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   82,   85,   88,   92,   94,
       98,  102,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  107,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  108,  108,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  110,  110,  110,  110,  110,  110,  110,  110,
      111,  111,  111,  111,  111,  112,  112,  112,  112,  112,
      112,  112,  112,  113,  113,  114,  114,  114,  114,  115,
      115,  115,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  117,

      117,  118,  118,  118,  118,  118,  118,  118,  119,  119,
      119,  119,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  122,  122,  122,  122,
      122,  123,  125,  125,  126,  128,  128,  129,  129,  129,
      129,  130,  130,  130,  130,  130,  130,  131,  132,  132,
      132,  132,  132,  132,  133,  134,  134,  134,  134,  135,
      135,  135,  135,  136,  136,  136,  136,  136,  136,  137,
      138,  138,  138,  139,  139,  139,  139,  140,  140,  140,
      141,  142,  142,  142,  143,  143,  143,  143,  144,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  145,  145,
      145,  146,  146,  147,  147,  147,  147,  148,  148,  149,
      149,  150,  150,  151,  152,  153,  153,  153,  153,  153,
      154,  154,  154,  154,  154,  154,  155,  155,  155,  156,
      156,  156,  156,  156,  156,  156,  156,  157,  158,  159,
      159,  159,  159,  159,  159,  159,  159,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  161,  162,  163,  163,
      164,  164,  165,  165,  166,  166,  166,  167,  167,  167,
      167,  167,  168,  168,  169,  170,  171,  171,  171,  172,
      173,  173,  173,  173,  173,  173,  174,  174,  174,  174,

      175,  175,  176,  176,  176,  176,  176,  176,  176,  176,
      177,  178,  178,  178,  178,  179,  180,  180,  181,  181,
      182,  182,  182,  183,  184,  185,  185,  186,  186,  186,
      186,  186,  186,  187,  188,  188,  189,  190,  191,  192,
      192,  192,  192,  193,  193,  194,  195,  197,  198,  198,
      199,  199,  200,  201,  201,  201,  201,  201,  202,  203,
      204,  204,  204,  205,  206,  206,  206,  206,  207,  207,
      207,  208,  208
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    3,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    5,    1,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    7,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,   12,
        1,   13,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   30,   37,   30,
        1,    1,    1,    1,    1,    1,   38,   15,   39,   40,

       41,   42,   43,   44,   45,   23,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   30,
       58,   59,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[60] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    4,
        5,    1,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    7,    6,    8,
        9,    6,   10,    6,    6,    6,   11,   10,   12,    6,
       13,   14,   15,    6,    6,    6,    6,   16,    6
    } ;

static yyconst short int yy_base[562] =
    {   0,
        0,    0,    0,    0,   59,   72,  712,  863,  863,  863,
      863,  701,   38,   51,   49,   57,   58,   53,   33,   59,
      656,  668,  663,  669,   70,   75,   76,   76,  656,   85,
       83,   92,   93,  650,   82,  100,  863,  863,  863,  863,
      863,  863,  690,  683,  640,    0,   99,  638,  637,  105,
      102,  104,  102,  116,  114,  641,   23,  648,  159,  106,
      647,  634,  647,  643,  636,  114,  127,  629,  619,  127,
      135,  126,  667,  615,  625,  624,  131,  614,  609,  617,
      604,  608,  617,    0,  617,  615,  123,  602,  601,  608,
      607,  136,  586,  137,    0,  141,  581,  142,  582,  147,

      574,  577,  620,  569,  605,  863,  563,  863,    0,  555,
        0,  568,  556,  557,  548,  542,  544,  540,  549,  534,
      533,  533,  547,  537,  526,  532,  532,  528,  537,  525,
      521,  519,  556,  502,  498,  512,  505,  498,  498,  502,
      508,  863,  492,  505,  504,  496,  486,  486,  490,  863,
      474,  476,  510,  147,  863,  471,  502,  457,    0,  456,
      450,  463,  468,  464,  863,  462,  448,  457,  863,  456,
      458,  863,    0,  443,  443,  440,  454,  446,  449,    0,
      479,  427,  436,  418,  147,    0,  419,  435,  424,  431,
      430,  432,  425,    0,  416,  414,  416,  410,  863,  404,

      863,  401,    0,  396,  405,  401,    0,  863,    0,  393,
      396,  863,    0,  376,  389,  376,  422,  388,  371,  418,
      373,  384,  367,  153,  378,    0,  370,  373,    0,  363,
        0,  372,  354,  361,  356,  863,    0,  402,    0,  357,
      863,  863,  349,  863,  863,    0,  863,    0,    0,  359,
      863,  357,  341,  351,  345,  347,  863,  863,  348,  344,
      339,  339,  338,  863,  863,  336,  380,  340,  863,  358,
      304,  300,  863,  315,  309,  348,    0,  304,  863,  863,
        0,    0,  863,  314,  311,  309,  863,  307,  303,  863,
      863,  302,  297,  863,  300,  288,  293,  863,  283,  296,

      282,  281,  281,  198,    0,  280,    0,  863,  287,  287,
      863,  269,  863,  284,  285,  279,  863,    0,  863,  263,
      863,  278,  863,  863,  863,  265,  272,    0,  270,  863,
        0,  270,  261,  268,  259,  863,    0,    0,  863,  219,
      202,  200,  206,  206,  199,  197,  863,  863,  863,  201,
        0,  200,    0,  199,  194,  197,  863,  205,  203,  202,
      202,  201,    0,    0,  187,  863,  193,  863,  195,  863,
      185,  863,    0,    0,  178,  182,  863,    0,  176,  192,
      180,  863,    0,  863,  863,  863,    0,  190,  863,  863,
      177,  188,  190,  189,  179,  863,    0,    0,  184,  863,

      170,  863,    0,    0,    0,    0,  174,  170,  180,  863,
      863,    0,  171,    0,  863,  863,    0,  863,    0,  863,
      166,    0,  863,  863,  863,  178,  863,    0,    0,  160,
      159,  166,  863,  863,    0,  863,  863,  863,  863,    0,
      162,  174,  863,  163,  863,  863,  863,  863,    0,  863,
        0,  863,  863,  174,  167,  159,  143,  863,  863,  863,
        0,  129,  863,  863,  118,   66,   68,  863,    0,    0,
      863,  863,  255,  268,  284,  300,  304,  320,  330,  345,
      358,  362,  378,  382,  386,  401,  416,  431,  435,  439,
      443,  450,  454,  458,  462,  478,  482,  486,  500,  512,

      516,  520,  524,  528,  532,  536,  540,  555,  559,  563,
      567,  571,  575,  590,  594,  598,  602,  611,  615,  619,
      623,  631,  635,  639,  643,  647,  651,  666,  670,  674,
      678,  693,  697,  701,  716,  720,  724,  728,  737,  752,
      756,  760,  764,  768,  772,  776,  780,  784,  788,  792,
      807,  811,  815,  819,  823,  827,  842,  846,  850,  854,
      858
    } ;

static yyconst short int yy_def[562] =
    {   0,
      472,    1,    1,    1,  473,  473,  472,  472,  472,  472,
      472,  474,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  474,  475,  472,  476,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      477,  478,  472,  472,  472,  472,  472,  472,  479,  472,
      472,  480,  472,  481,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  482,  472,  472,  472,  472,  472,

      472,  472,  472,  472,  475,  472,  472,  472,  483,  472,
      484,  472,  472,  472,  472,  472,  472,  485,  472,  472,
      472,  486,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  487,  472,  472,  472,
      472,  472,  488,  478,  472,  472,  489,  472,  490,  472,
      472,  472,  491,  472,  472,  472,  480,  472,  472,  472,
      472,  472,  492,  472,  472,  472,  472,  472,  472,  493,
      494,  472,  472,  495,  472,  496,  472,  472,  472,  472,
      472,  472,  472,  497,  498,  472,  499,  472,  472,  472,

      472,  472,  500,  472,  472,  472,  501,  472,  502,  472,
      472,  472,  503,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  504,  472,  472,  505,  472,
      506,  472,  472,  472,  507,  472,  508,  472,  509,  472,
      472,  472,  472,  472,  472,  510,  472,  511,  512,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  513,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  514,  472,  472,  472,
      515,  516,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  517,  472,  472,  472,  472,  472,

      472,  472,  472,  518,  519,  472,  520,  472,  472,  521,
      472,  472,  472,  517,  472,  472,  472,  522,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  523,  472,  472,
      524,  472,  472,  472,  472,  472,  525,  526,  472,  472,
      472,  472,  472,  472,  527,  472,  472,  472,  472,  472,
      528,  472,  529,  472,  472,  472,  472,  472,  472,  472,
      472,  521,  530,  518,  531,  472,  472,  472,  472,  472,
      472,  472,  532,  533,  472,  534,  472,  535,  472,  472,
      472,  472,  536,  472,  472,  472,  537,  538,  472,  472,
      539,  472,  472,  472,  519,  472,  540,  541,  472,  472,

      472,  472,  542,  543,  544,  545,  472,  472,  472,  472,
      472,  546,  472,  547,  472,  472,  548,  472,  549,  472,
      550,  551,  472,  472,  472,  472,  472,  552,  553,  472,
      472,  472,  472,  472,  554,  472,  472,  472,  472,  555,
      556,  472,  472,  472,  472,  472,  472,  472,  557,  472,
      558,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      559,  472,  472,  472,  472,  472,  472,  472,  560,  561,
      472,    0,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,

      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472
    } ;

static yyconst short int yy_nxt[923] =
    {   0,
        8,    9,    8,   10,    8,   11,    8,    8,    8,    8,
       11,   12,    8,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   11,
       29,   30,   31,   11,   11,   32,   33,   13,   15,   16,
       17,   18,   19,   20,   34,   23,   24,   25,   26,   27,
       28,   29,   35,   31,   11,   11,   36,   33,   11,   37,
       38,   37,   39,   40,  128,   41,   37,   42,   37,  129,
       37,   37,   37,   38,   37,   39,   40,   68,   41,   37,
       42,   37,   45,   37,   37,   46,   53,   69,   49,   47,
       48,   50,   54,   65,   56,   62,   70,   57,   55,   71,

       51,   58,   66,   72,   67,   52,   59,   77,   60,   63,
      414,   61,   80,   64,   83,   81,   87,   84,   91,   78,
       88,  125,   85,  470,   82,   92,   94,   79,   92,   97,
       89,   86,   95,  100,   96,   93,   98,  104,   93,  109,
      151,   99,  101,  119,   98,  113,  114,  102,  110,   99,
      134,  116,  121,  122,  117,  135,  123,  120,  115,  118,
      124,  131,  131,  141,  143,  142,  148,  144,  156,  162,
      126,  145,  175,  157,  176,  373,  181,  184,  187,  163,
      182,  152,  149,  190,  193,  469,  153,  271,  185,  472,
      191,  467,  154,  305,  472,  188,  272,  306,  307,  194,

      367,  367,  393,  393,  466,  132,  456,  133,  394,  394,
      457,  465,  462,  406,  461,  455,  454,  451,  449,  444,
      442,  441,  440,  435,  159,  432,  431,  430,  429,  428,
      426,  207,  422,  421,  419,  417,  353,  414,  413,  412,
      373,  409,  408,  407,  406,  405,  404,  403,  401,  399,
      398,  397,  395,  392,  342,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   44,  391,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,

      108,  108,  388,  108,  150,  150,  150,  150,  387,  386,
      385,  383,  381,  380,  150,  379,  378,  150,  376,  150,
      155,  155,  375,  155,  472,  374,  373,  371,  369,  155,
      165,  165,  365,  165,  364,  363,  362,  361,  360,  359,
      358,  356,  355,  354,  165,  169,  169,  353,  169,  352,
      351,  350,  249,  346,  345,  344,  343,  169,  172,  172,
      342,  172,  186,  341,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  199,  199,
      340,  199,  201,  201,  339,  201,  208,  208,  338,  208,
      337,  335,  334,  333,  332,  331,  330,  329,  328,  327,

      208,  212,  212,  326,  212,  322,  154,  320,  318,  316,
      315,  314,  312,  310,  309,  212,  236,  236,  307,  236,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      236,  241,  241,  293,  241,  244,  244,  292,  244,  247,
      247,  203,  247,  251,  251,  289,  251,  288,  286,  251,
      257,  257,  285,  257,  264,  264,  284,  264,  265,  265,
      265,  265,  269,  269,  276,  269,  282,  281,  194,  278,
      203,  277,  276,  275,  274,  270,  268,  269,  273,  273,
      267,  273,  279,  279,  266,  279,  280,  280,  263,  280,
      262,  261,  260,  259,  258,  256,  167,  255,  472,  280,

      283,  283,  254,  283,  253,  252,  250,  249,  248,  246,
      245,  283,  287,  287,  243,  287,  290,  290,  242,  290,
      291,  291,  240,  291,  294,  294,  239,  294,  308,  308,
      148,  308,  311,  311,  238,  311,  313,  313,  237,  313,
      317,  317,  235,  317,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  317,  319,  319,  224,  319,  321,
      321,  223,  321,  323,  323,  222,  323,  324,  324,  221,
      324,  325,  325,  220,  325,  336,  336,  219,  336,  218,
      217,  216,  126,  215,  214,  213,  211,  111,  210,  336,
      347,  347,  209,  347,  348,  348,  207,  348,  349,  349,

      206,  349,  357,  357,  205,  357,  204,  203,  202,  200,
      357,  366,  366,  198,  366,  368,  368,  106,  368,  370,
      370,  197,  370,  372,  372,  196,  372,  194,  195,  192,
      372,  377,  377,  189,  377,  382,  382,  183,  382,  384,
      384,  180,  384,  389,  389,  179,  389,  390,  390,  178,
      390,  396,  396,  177,  396,  174,  173,  171,  170,  168,
      167,  166,  164,  161,  160,  396,  400,  400,  159,  400,
      402,  402,  158,  402,  410,  410,  147,  410,  411,  411,
      146,  411,  140,  139,  138,  137,  136,  130,  127,  112,
      111,  107,  411,  415,  415,  106,  415,  416,  416,  472,

      416,  418,  418,  103,  418,   90,   76,   75,   74,   73,
       43,  472,  472,  472,  472,  418,  420,  420,  472,  420,
      423,  423,  472,  423,  424,  424,  472,  424,  425,  425,
      472,  425,  472,  472,  472,  472,  425,  427,  427,  472,
      427,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  427,  433,  433,  472,  433,  434,  434,  472,  434,
      436,  436,  472,  436,  437,  437,  472,  437,  438,  438,
      472,  438,  439,  439,  472,  439,  443,  443,  472,  443,
      445,  445,  472,  445,  446,  446,  472,  446,  447,  447,
      472,  447,  448,  448,  472,  448,  472,  472,  472,  472,

      472,  472,  472,  472,  472,  472,  448,  450,  450,  472,
      450,  452,  452,  472,  452,  453,  453,  472,  453,  458,
      458,  472,  458,  459,  459,  472,  459,  460,  460,  472,
      460,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  460,  463,  463,  472,  463,  464,  464,  472,  464,
      468,  468,  472,  468,  471,  471,  472,  471,  372,  372,
      472,  372,    7,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,

      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472
    } ;

static yyconst short int yy_chk[923] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    5,   57,    5,    5,    5,    5,   57,
        5,    5,    6,    6,    6,    6,    6,   19,    6,    6,
        6,    6,   13,    6,    6,   13,   15,   19,   14,   13,
       13,   14,   15,   18,   16,   17,   20,   16,   15,   20,

       14,   16,   18,   20,   18,   14,   16,   25,   16,   17,
      467,   16,   26,   17,   27,   26,   28,   27,   30,   25,
       28,   55,   27,  466,   26,   35,   31,   25,   30,   32,
       28,   27,   31,   33,   31,   35,   32,   36,   30,   47,
       71,   32,   33,   52,   36,   50,   50,   33,   47,   36,
       60,   51,   53,   53,   51,   60,   54,   52,   50,   51,
       54,   59,   59,   66,   67,   66,   70,   67,   72,   77,
       55,   67,   87,   72,   87,  465,   92,   94,   96,   77,
       92,   71,   70,   98,  100,  462,   71,  185,   94,  154,
       98,  457,   71,  224,  154,   96,  185,  224,  456,  100,

      304,  304,  342,  342,  455,   59,  432,   59,  343,  343,
      432,  454,  444,  442,  441,  431,  430,  426,  421,  413,
      409,  408,  407,  401,  399,  395,  394,  393,  392,  391,
      388,  381,  380,  379,  376,  375,  371,  369,  367,  365,
      362,  361,  360,  359,  358,  356,  355,  354,  352,  350,
      346,  345,  344,  341,  343,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  474,  340,  474,  474,  474,  474,  474,  474,  474,
      474,  474,  474,  474,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,

      476,  476,  335,  476,  477,  477,  477,  477,  334,  333,
      332,  329,  327,  326,  477,  322,  320,  477,  316,  477,
      478,  478,  315,  478,  314,  312,  310,  309,  306,  478,
      479,  479,  303,  479,  302,  301,  300,  299,  297,  296,
      295,  293,  292,  289,  479,  480,  480,  288,  480,  286,
      285,  284,  278,  276,  275,  274,  272,  480,  481,  481,
      271,  481,  482,  270,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  483,  483,
      268,  483,  484,  484,  267,  484,  485,  485,  266,  485,
      263,  262,  261,  260,  259,  256,  255,  254,  253,  252,

      485,  486,  486,  250,  486,  243,  240,  238,  235,  234,
      233,  232,  230,  228,  227,  486,  487,  487,  225,  487,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      487,  488,  488,  211,  488,  489,  489,  210,  489,  490,
      490,  206,  490,  491,  491,  205,  491,  204,  202,  491,
      492,  492,  200,  492,  493,  493,  198,  493,  494,  494,
      494,  494,  495,  495,  197,  495,  196,  195,  193,  192,
      191,  190,  189,  188,  187,  184,  183,  495,  496,  496,
      182,  496,  497,  497,  181,  497,  498,  498,  179,  498,
      178,  177,  176,  175,  174,  171,  170,  168,  167,  498,

      499,  499,  166,  499,  164,  163,  162,  161,  160,  158,
      157,  499,  500,  500,  156,  500,  501,  501,  153,  501,
      502,  502,  152,  502,  503,  503,  151,  503,  504,  504,
      149,  504,  505,  505,  148,  505,  506,  506,  147,  506,
      507,  507,  146,  507,  145,  144,  143,  141,  140,  139,
      138,  137,  136,  135,  507,  508,  508,  134,  508,  509,
      509,  133,  509,  510,  510,  132,  510,  511,  511,  131,
      511,  512,  512,  130,  512,  513,  513,  129,  513,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  513,
      514,  514,  118,  514,  515,  515,  117,  515,  516,  516,

      116,  516,  517,  517,  115,  517,  114,  113,  112,  110,
      517,  518,  518,  107,  518,  519,  519,  105,  519,  520,
      520,  104,  520,  521,  521,  103,  521,  102,  101,   99,
      521,  522,  522,   97,  522,  523,  523,   93,  523,  524,
      524,   91,  524,  525,  525,   90,  525,  526,  526,   89,
      526,  527,  527,   88,  527,   86,   85,   83,   82,   81,
       80,   79,   78,   76,   75,  527,  528,  528,   74,  528,
      529,  529,   73,  529,  530,  530,   69,  530,  531,  531,
       68,  531,   65,   64,   63,   62,   61,   58,   56,   49,
       48,   45,  531,  532,  532,   44,  532,  533,  533,   43,

      533,  534,  534,   34,  534,   29,   24,   23,   22,   21,
       12,    7,    0,    0,    0,  534,  535,  535,    0,  535,
      536,  536,    0,  536,  537,  537,    0,  537,  538,  538,
        0,  538,    0,    0,    0,    0,  538,  539,  539,    0,
      539,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  539,  540,  540,    0,  540,  541,  541,    0,  541,
      542,  542,    0,  542,  543,  543,    0,  543,  544,  544,
        0,  544,  545,  545,    0,  545,  546,  546,    0,  546,
      547,  547,    0,  547,  548,  548,    0,  548,  549,  549,
        0,  549,  550,  550,    0,  550,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  550,  551,  551,    0,
      551,  552,  552,    0,  552,  553,  553,    0,  553,  554,
      554,    0,  554,  555,  555,    0,  555,  556,  556,    0,
      556,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  556,  557,  557,    0,  557,  558,  558,    0,  558,
      559,  559,    0,  559,  560,  560,    0,  560,  561,  561,
        0,  561,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,

      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pirate.l"
#define INITIAL 0
/* GNU Talkfilters
   Copyright (C) 1998-2003 Free Software Foundation, Inc.

   This file is part of GNU Talkfilters

   GNU Talkfilters is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2, or (at
   your option) any later version.

   This software is distributed in the hope that it will be amusing, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this software; see the file COPYING.  If not, write to the
   Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
*/
#line 34 "pirate.l"

#include "common.h"
#include "talkfilters.h"

#define YY_DECL int yylex(gtf_databuf_t *buf)

#define NIW 1
#define INW 2

#line 833 "pirate.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 49 "pirate.l"


#line 987 "pirate.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 473 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 863 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */

case 1:
YY_RULE_SETUP
#line 53 "pirate.l"
gtf_echo(); // don't damage HTML tags
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 55 "pirate.l"
gtf_echo();
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 56 "pirate.l"
gtf_puts_case("me");
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "pirate.l"
gtf_puts_case("admiral");
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 58 "pirate.l"
gtf_puts_case("cap'n");
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 59 "pirate.l"
gtf_puts_case("crew");
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 60 "pirate.l"
gtf_puts_case("scuttle");
	YY_BREAK
case 8:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 61 "pirate.l"
gtf_puts_case("scuttled");
	YY_BREAK
case 9:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 62 "pirate.l"
gtf_puts_case("meself");
	YY_BREAK
case 10:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "pirate.l"
gtf_puts_case("yer");
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 64 "pirate.l"
gtf_puts_case("ye");
	YY_BREAK
case 12:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 65 "pirate.l"
gtf_puts_case("matey");
	YY_BREAK
case 13:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "pirate.l"
gtf_puts_case("maties");
	YY_BREAK
case 14:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 67 "pirate.l"
gtf_puts_case("shipmate");
	YY_BREAK
case 15:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 68 "pirate.l"
gtf_puts_case("shipmates");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "pirate.l"
gtf_puts_case("landlubber");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "pirate.l"
gtf_puts_case("landlubbers");
	YY_BREAK
case 18:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "pirate.l"
gtf_puts_case("scurvey dogs");
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 72 "pirate.l"
gtf_puts_case("afore");
	YY_BREAK
case 20:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "pirate.l"
gtf_puts_case("auld");
	YY_BREAK
case 21:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "pirate.l"
gtf_puts_case("th'");
	YY_BREAK
case 22:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "pirate.l"
gtf_puts_case("o'");
	YY_BREAK
case 23:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "pirate.l"
gtf_puts_case("dern't");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "pirate.l"
gtf_puts_case("ne'er"); BEGIN(INW);
	YY_BREAK
case 25:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 78 "pirate.l"
gtf_puts_case("e'er");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "pirate.l"
gtf_puts_case("o'er"); BEGIN(INW);
	YY_BREAK
case 27:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 80 "pirate.l"
gtf_puts_case("aye");
	YY_BREAK
case 28:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 81 "pirate.l"
gtf_puts_case("nay");
	YY_BREAK
case 29:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 82 "pirate.l"
gtf_puts_case("dinna");
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 83 "pirate.l"
gtf_puts_case("ha'nae");
	YY_BREAK
case 31:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 84 "pirate.l"
gtf_puts_case("di'nae");
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 85 "pirate.l"
gtf_puts_case("weren't");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "pirate.l"
gtf_puts_case("fer"); BEGIN(INW);
	YY_BREAK
case 34:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 87 "pirate.l"
gtf_puts_case("betwixt");
	YY_BREAK
case 35:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 88 "pirate.l"
gtf_puts_case("aroun'");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "pirate.l"
gtf_puts_case("t'"); BEGIN(INW);
	YY_BREAK
case 37:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 90 "pirate.l"
gtf_puts("'Tis");
	YY_BREAK
case 38:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 91 "pirate.l"
gtf_puts("'tis");
	YY_BREAK
case 39:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 92 "pirate.l"
gtf_puts_case("wench");
	YY_BREAK
case 40:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "pirate.l"
gtf_puts_case("lady");
	YY_BREAK
case 41:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 94 "pirate.l"
gtf_puts_case("lass");
	YY_BREAK
case 42:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 95 "pirate.l"
gtf_puts_case("lassies");
	YY_BREAK
case 43:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
#line 97 "pirate.l"
case 44:
#line 98 "pirate.l"
case 45:
#line 99 "pirate.l"
case 46:
YY_RULE_SETUP
#line 99 "pirate.l"
gtf_puts_case("lubber");
	YY_BREAK
case 47:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 100 "pirate.l"
gtf_puts_case("lad");
	YY_BREAK
case 48:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 101 "pirate.l"
gtf_puts_case("laddies");
	YY_BREAK
case 49:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 102 "pirate.l"
gtf_puts_case("be");
	YY_BREAK
case 50:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 103 "pirate.l"
gtf_puts_case("be");
	YY_BREAK
case 51:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 104 "pirate.l"
gtf_puts_case("little sandcrabs");
	YY_BREAK
case 52:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 105 "pirate.l"
gtf_puts_case("minnows");
	YY_BREAK
case 53:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 106 "pirate.l"
gtf_puts_case("that scurvey dog");
	YY_BREAK
case 54:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 107 "pirate.l"
gtf_puts_case("that comely wench");
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "pirate.l"
gtf_puts_case("that drunken sailor.");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "pirate.l"
gtf_puts_case("that comely lass.");
	YY_BREAK
case 57:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "pirate.l"
gtf_puts_case("that ornery cuss");
	YY_BREAK
case 58:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 111 "pirate.l"
gtf_puts_case("that winsome lass");
	YY_BREAK
case 59:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "pirate.l"
gtf_puts_case("he be");
	YY_BREAK
case 60:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 113 "pirate.l"
gtf_puts_case("she be");
	YY_BREAK
case 61:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 114 "pirate.l"
gtf_puts_case("they be");
	YY_BREAK
case 62:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 115 "pirate.l"
gtf_puts_case("were bein'");
	YY_BREAK
case 63:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 116 "pirate.l"
gtf_puts_case("avast");
	YY_BREAK
case 64:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 117 "pirate.l"
gtf_puts_case("high seas");
	YY_BREAK
case 65:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 118 "pirate.l"
gtf_puts_case("chow");
	YY_BREAK
case 66:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 119 "pirate.l"
gtf_puts_case("sea");
	YY_BREAK
case 67:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 120 "pirate.l"
gtf_puts_case("high seas");
	YY_BREAK
case 68:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 121 "pirate.l"
gtf_puts_case("seas");
	YY_BREAK
case 69:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 122 "pirate.l"
gtf_puts_case("river");
	YY_BREAK
case 70:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 123 "pirate.l"
gtf_puts_case("rivers");
	YY_BREAK
case 71:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 124 "pirate.l"
gtf_puts_case("ocean");
	YY_BREAK
case 72:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 125 "pirate.l"
gtf_puts_case("oceans");
	YY_BREAK
case 73:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 126 "pirate.l"
gtf_puts_case("boat");
	YY_BREAK
case 74:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 127 "pirate.l"
gtf_puts_case("boats");
	YY_BREAK
case 75:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 128 "pirate.l"
gtf_puts_case("schooner");
	YY_BREAK
case 76:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "pirate.l"
gtf_puts_case("schooners");
	YY_BREAK
case 77:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "pirate.l"
gtf_puts_case("ship");
	YY_BREAK
case 78:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 131 "pirate.l"
gtf_puts_case("flying machine");
	YY_BREAK
case 79:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 132 "pirate.l"
gtf_puts_case("contraption");
	YY_BREAK
case 80:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 133 "pirate.l"
gtf_puts_case("sailing");
	YY_BREAK
case 81:
#line 135 "pirate.l"
case 82:
YY_RULE_SETUP
#line 135 "pirate.l"
gtf_puts_case("Arrrr!"); BEGIN(NIW);
	YY_BREAK
case 83:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 136 "pirate.l"
gtf_puts_case("dungbie");
	YY_BREAK
case 84:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 137 "pirate.l"
gtf_puts_case("hornswaggle");
	YY_BREAK
case 85:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 138 "pirate.l"
gtf_puts_case("hornswaggled");
	YY_BREAK
case 86:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 139 "pirate.l"
gtf_puts_case("buccaneer");
	YY_BREAK
case 87:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 140 "pirate.l"
gtf_puts_case("grog");
	YY_BREAK
case 88:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 141 "pirate.l"
gtf_puts_case("bilge");
	YY_BREAK
case 89:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 142 "pirate.l"
gtf_puts_case("keel-haul");
	YY_BREAK
case 90:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 143 "pirate.l"
gtf_puts_case("keel-hauled");
	YY_BREAK
case 91:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 144 "pirate.l"
gtf_puts_case("doubloon");
	YY_BREAK
case 92:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 145 "pirate.l"
gtf_puts_case("doubloons");
	YY_BREAK
case 93:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 146 "pirate.l"
{ switch(gtf_random(2))
                             {
                             case 0:
                               gtf_puts_case("gold");
                               break;
                             case 1:
                               gtf_puts_case("treasure");
                               break;
                             }
                          }
	YY_BREAK
case 94:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 156 "pirate.l"
gtf_puts_case("sail");
	YY_BREAK
case 95:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 157 "pirate.l"
gtf_puts_case("sailed");
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 159 "pirate.l"
{ BEGIN(INW); gtf_echo(); }
	YY_BREAK


case 97:
YY_RULE_SETUP
#line 165 "pirate.l"
{ switch(gtf_random(10))
                            {
                            case 0:
                              gtf_puts("! Walk the plank!");
                              break;
                            case 1:
                              gtf_puts(", Arrrr!");
                              break;
                            case 2:
                              gtf_puts(", Yaaarrrr!");
                              break;
                            case 3:
                              gtf_puts(", and dinna spare the whip!");
                              break;
                            case 4:
                              gtf_puts("! Shiver me timbers!");
                              break;
                            case 5:
                              gtf_puts("! Fire the cannons!");
                              break;
                            case 6:
                              gtf_puts("! We'll keel-haul ye!");
                              break;
                            default:
                              gtf_echo();
                            }
                          BEGIN(NIW);
                        }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 194 "pirate.l"
{ switch(gtf_random(10))
                            {
                            case 0:
                              gtf_puts(", aye,");
                              break;
                            case 1:
                              gtf_puts(", I'll warrant ye,");
                              break;
                            case 2:
                              gtf_puts(", to be sure,");
                              break;
                            case 3:
                              gtf_puts(", arrrr,");
                              break;
                            case 4:
                              gtf_puts(", by Blackbeard's sword,");
                              break;
                            default:
                              gtf_echo();
                            }
                          BEGIN(NIW);
                        }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 217 "pirate.l"
{ switch(gtf_random(20))
                            {
                            case 0:
                              gtf_puts(", and a bottle of rum!");
                              break;
                            case 1:
                              gtf_puts(". And swab the deck!");
                              break;
                            case 2:
                              gtf_puts(", by Davy Jones's locker.");
                              break;
                            case 3:
                              gtf_puts(", ye scurvey dog.");
                              break;
                            case 4:
                              gtf_puts(", I'll warrant ye.");
                              break;
                            case 5:
                              gtf_puts(", arrrr.");
                              break;
                            case 6:
                              gtf_puts(", with a chest full a' booty.");
                              break;
                            case 7:
                              gtf_puts(". Pass the grog!");
                              break;
                            case 8:
                              gtf_puts(". Hoist the mainsail!");
                              break;
                            default:
                              gtf_echo();
                            }
                          BEGIN(NIW);
                        }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 252 "pirate.l"
BEGIN(NIW); unput(yytext[0]);
	YY_BREAK

case 101:
YY_RULE_SETUP
#line 256 "pirate.l"
/* ignore trailing EOT character */
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 257 "pirate.l"
gtf_echo();
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 259 "pirate.l"
ECHO;
	YY_BREAK
#line 1931 "pirate.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NIW):
			case YY_STATE_EOF(INW):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 473 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 473 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 472);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 259 "pirate.l"


/*
 */

#ifdef LIBRARY_MODE

int gtf_filter_pirate(const char *input, char *buf, size_t bufsz)
  {
  gtf_databuf_t buffer;
  YY_BUFFER_STATE _yybuf;

  gtf_strbuf_init(&buffer, buf, bufsz);
  _yybuf = yy_scan_string(input);
  yylex(&buffer);
  yy_delete_buffer(_yybuf);
  gtf_reset();

  return(buffer.overflow);
  }

int __gtf_filter_pirate(const char *input, char *buf, size_t bufsz)
{
  return(gtf_filter_pirate(input, buf, bufsz));
}

#else /* LIBRARY_MODE */

int main(int argc, char **argv)
  {
  gtf_parse_args();
  gtf_random_seed();

  yylex(NULL);

  return(EXIT_SUCCESS);
  }

#endif /* LIBRARY_MODE */

/* end of source file */
